# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

def moviesi_information_app
pod 'SDWebImage', '~> 5.0'
pod 'Cosmos', '~> 23.0'
end

target 'MoviesInformationApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

moviesi_information_app

  # Pods for MoviesInformationApp

  target 'MoviesInformationAppTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
